version: "3"
services:
  nb:
    build: .
    restart: "no"
    environment:
      - http_proxy=$http_proxy
      - HTTP_PROXY=$HTTP_PROXY
      - https_proxy=$https_proxy
      - HTTPS_PROXY=$HTTPS_PROXY
    volumes:
      - ${PWD}/data:/data
      - ${PWD}/data_raw:/data_raw
      - ${PWD}/code:/code
    ports:
      - "80:5080"
